spring:
  config:
    import: optional:application-secret.yml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG


server:
  address: 0.0.0.0
  port: 8080





