spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sport_app?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

    username: root
    password: NicolaHristov13

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  open-in-view: false

server:
  port: 8080
