spring:
  config:
    import:
      - "optional:file:./.env[.properties]"
      - "optional:secrets:/etc/secrets/application-secret.yml"
      - "application-planetscale.yml"
  profiles:
    active: planetscale




